export enum Action {
    UPDATE_CODE_EDITOR_CONTENT = 'UPDATE_CODE_EDITOR_CONTENT',
    UPDATE_COMPILATION_OUTPUT = 'UPDATE_COMPILATION_OUTPUT',
    UPDATE_ACTIVE_POPUP_TYPE = 'UPDATE_ACTIVE_POPUP_TYPE'
}
