export enum Action {
    UPDATE_CODE_EDITOR_CONTENT = 'UPDATE_CODE_EDITOR_CONTENT',
    UPDATE_COMPILATION_OUTPUT = 'UPDATE_COMPILATION_OUTPUT',
    UPDATE_IMPORT_POPUP_STATUS = 'UPDATE_IMPORT_POPUP_STATUS',
    UPDATE_EXPORT_POPUP_STATUS = 'UPDATE_EXPORT_POPUP_STATUS',
    UPDATE_OPTIONS_POPUP_STATUS = 'UPDATE_OPTIONS_POPUP_STATUS',
    UPDATE_ABOUT_POPUP_STATUS = 'UPDATE_ABOUT_POPUP_STATUS',
}
